name: adamimic
channels:
  - defaults
dependencies:
  - python=3.8
  - tensorboard
  - tqdm
  - numpy=1.20.3
  - seaborn
  - GitPython
  - pydelatin
  - hydra-core
  - pip
  - wandb
  - wcwidth
  - pip:
    - git+https://github.com/KellerJordan/Muon
    - pyfqmr
